version: "3.9"

services:

# https://hub.docker.com/r/xhofe/alist
  alist:
    image: xhofe/alist:latest
    container_name: alist
    environment:
      - PUID=65534
      - PGID=65534
      - Qbittorrent_ADDRESS=qbittorrentee
      - Qbittorrent_PORT=8181
    volumes:
      - ${PWD}/alist:/opt/alist/data
    ports:
      - 5244:5244 
    restart: always
    networks:
      - alistbridge

# https://hub.docker.com/r/superng6/qbittorrentee
  qbittorrent:
    image: superng6/qbittorrentee:latest
    container_name: qbittorrentee
    environment:
      - PUID=65534
      - PGID=65534
      - TZ=Asia/Shanghai
      - WEBUIPORT=8181
    volumes:
      - ${PWD}/qbittorrent/config:/config       # config
      - ${PWD}/qbittorrent/downloads:/downloads # Downloads
      - ${PWD}/qbittorrent/data:/opt/alist/data # Data
    ports:
      - 8181:8181
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      - alistbridge

  # Aria2-pro-docker official guide: https://github.com/P3TERX/Aria2-Pro-Docker/blob/master/docker-compose.yml
  Aria2-Pro:
    container_name: aria2-pro
    image: p3terx/aria2-pro
    environment:
      - PUID=65534
      - PGID=65534
      - UMASK_SET=022
      - RPC_SECRET=REPLACE_WITH_YOUR_OWN_ARIA2_RPC_SECRET # Please set your own RPC secret.
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=false
      - UPDATE_TRACKERS=true
      - CUSTOM_TRACKER_URL=
      - TZ=Asia/Shanghai
    volumes:
      - ${PWD}/aria2/config:/config # 配置文件
      - ${PWD}/aria2/downloads:/downloads # UI界面手动添加下载的路径映射
      - ${PWD}/aria2/data:/opt/alist/data # 自行修改配置文件具体路径，我使用绝对路径
    ports:
      - "6800:6800"
      - "6888:6888"
      - "6888:6888/udp"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m
    networks:
      - alistbridge

  AriaNg:
    image: p3terx/ariang:latest
    container_name: ariang
    environment:
      - PUID=65534
      - PGID=65534
    command: --port 6880 --ipv6
    ports:
      - "6880:6880"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m
    networks:
      - alistbridge

networks:
  alistbridge:
    driver: bridge
